MohamedRejeb/Calf

sample/web-js/src/jsMain/resources/index.html, sample/web-wasm/src/wasmJsMain/resources/index.html
Small changes, but not small improvement =)
=> Add meta viewport setting for better user experience on mobile devices

calf-file-picker/src/iosMain/kotlin/com.mohamedrejeb.calf.picker/FilePickerLauncher.ios.kt, calf-file-picker/src/iosMain/kotlin/com.mohamedrejeb.calf.picker/TempFile.kt
=> Create iOS temp file in file picker

calf-core/src/commonMain/kotlin/com.mohamedrejeb.calf/core/ExperimentalCalfApi.kt, calf-core/src/commonMain/kotlin/com.mohamedrejeb.calf/core/InternalCalfApi.kt, calf-file-picker/src/iosMain/kotlin/com.mohamedrejeb.calf.picker/FilePickerLauncher.ios.kt, calf-file-picker/src/iosMain/kotlin/com.mohamedrejeb.calf.picker/TempFile.kt, calf-io/src/iosMain/kotlin/com.mohamedrejeb.calf/io/KmpFile.ios.kt, docs/filepicker.md
=> Add a reference to the original NSURL on iOS and skip creating temp file for directories.

calf-file-picker/src/iosMain/kotlin/com.mohamedrejeb.calf.picker/FilePickerLauncher.ios.kt, calf-file-picker/src/iosMain/kotlin/com.mohamedrejeb.calf.picker/TempFile.kt
=> Use PHPicker for FilePickerFileType.Video and FilePickerFileType.ImageVideo

calf-permissions/src/androidMain/kotlin/com/mohamedrejeb/calf/permissions/PermissionsUtil.android.kt, calf-permissions/src/commonMain/kotlin/com.mohamedrejeb.calf/permissions/PermissionState.kt, calf-permissions/src/iosMain/kotlin/com.mohamedrejeb.calf/permissions/PermissionsUtil.kt, calf-permissions/src/iosMain/kotlin/com.mohamedrejeb.calf/permissions/helper/LocalNotificationPermissionHelper.kt, docs/permissions.md, sample/android/src/main/AndroidManifest.xml, sample/common/src/commonMain/kotlin/com.mohamedrejeb.calf.sample/screens/PermissionsScreen.kt, sample/ios/Calf/Info.plist
Hi @MohamedRejeb!
Thanks for the awesome library.
For my application I require local notification support, was a breeze to implement.
=> Add local notification permission

docs/filepicker.md
As we talked [here](https://github.com/MohamedRejeb/Calf/pull/84#issuecomment-2205478410), this PR adds the documentation regarding the Coil package.
=> Document Coil package

calf-ui/src/iosMain/kotlin/com/mohamedrejeb/calf/ui/sheet/AdaptiveBottomSheet.ios.kt
=> Fix using native ios components inside AdaptiveBottomSheet

calf-ui/src/commonMain/kotlin/com/mohamedrejeb/calf/ui/sheet/AdaptiveSheetState.kt
=> Fix rememberSheetState losing sheet state

calf-ui/src/iosMain/kotlin/com/mohamedrejeb/calf/ui/datepicker/AdaptiveDatePicker.ios.kt, calf-ui/src/iosMain/kotlin/com/mohamedrejeb/calf/ui/datepicker/DatePickerManager.kt
=> Use initialSelectedDateMillis as the initial date on iOS if it exists.

calf-ui/src/iosMain/kotlin/com/mohamedrejeb/calf/ui/datepicker/AdaptiveDatePicker.ios.kt, calf-ui/src/iosMain/kotlin/com/mohamedrejeb/calf/ui/datepicker/DatePickerManager.kt
=> AdaptiveDatePicker: use DatePickerColors on iOS

gradle/libs.versions.toml
=> Update Kotlin to 2.0.10

build.gradle.kts, calf-permissions/src/androidMain/kotlin/com/mohamedrejeb/calf/permissions/MutableMultiplePermissionsState.android.kt, calf-permissions/src/androidMain/kotlin/com/mohamedrejeb/calf/permissions/MutablePermissionState.android.kt, calf-permissions/src/commonMain/kotlin/com.mohamedrejeb.calf/permissions/MutablePermissionState.kt, calf-permissions/src/desktopMain/kotlin/com/mohamedrejeb/calf/permissions/MutablePermissionState.desktop.kt, calf-permissions/src/iosMain/kotlin/com.mohamedrejeb.calf/permissions/MutablePermissionState.ios.kt, calf-permissions/src/jsMain/kotlin/com.mohamedrejeb.calf/permissions/MutablePermissionState.js.kt, calf-permissions/src/wasmJsMain/kotlin/com.mohamedrejeb.calf/permissions/MutablePermissionState.wasmJs.kt, convention-plugins/build.gradle.kts
=> Fix Permission.Notification crash in IOS

calf-permissions/src/iosMain/kotlin/com.mohamedrejeb.calf/permissions/MutablePermissionState.ios.kt, calf-permissions/src/iosMain/kotlin/com.mohamedrejeb.calf/permissions/PermissionsUtil.kt, calf-permissions/src/iosMain/kotlin/com.mohamedrejeb.calf/permissions/helper/AVCapturePermissionHelper.kt, calf-permissions/src/iosMain/kotlin/com.mohamedrejeb.calf/permissions/helper/BluetoothPermissionHelper.kt, calf-permissions/src/iosMain/kotlin/com.mohamedrejeb.calf/permissions/helper/GalleryPermissionHelper.kt, calf-permissions/src/iosMain/kotlin/com.mohamedrejeb.calf/permissions/helper/LocalNotificationPermissionHelper.kt, calf-permissions/src/iosMain/kotlin/com.mohamedrejeb.calf/permissions/helper/LocationPermissionHelper.kt, calf-permissions/src/iosMain/kotlin/com.mohamedrejeb.calf/permissions/helper/PermissionHelper.kt, calf-permissions/src/iosMain/kotlin/com.mohamedrejeb.calf/permissions/helper/RemoteNotificationPermissionHelper.kt
=> Handle PermissionStatus.Denied.shouldShowRationale on iOS

calf-file-picker/src/iosMain/kotlin/com.mohamedrejeb.calf.picker/FilePickerLauncher.ios.kt
=> Remove iOS 15.0+ PHPickerConfiguration APIs

calf-ui/src/iosMain/kotlin/com/mohamedrejeb/calf/ui/datepicker/AdaptiveDatePicker.ios.kt, calf-ui/src/iosMain/kotlin/com/mohamedrejeb/calf/ui/datepicker/DatePickerManager.kt
=> Fix AdaptiveDatePicker cutoff when using padding on iOS

calf-permissions/src/androidMain/kotlin/com/mohamedrejeb/calf/permissions/MutablePermissionState.android.kt
=> Fix Notification Permission issue on Android 12 and below

calf-permissions/src/androidMain/kotlin/com/mohamedrejeb/calf/permissions/PermissionsUtil.android.kt, calf-permissions/src/commonMain/kotlin/com.mohamedrejeb.calf/permissions/PermissionState.kt, calf-permissions/src/iosMain/kotlin/com.mohamedrejeb.calf/permissions/PermissionsUtil.ios.kt, calf-permissions/src/iosMain/kotlin/com.mohamedrejeb.calf/permissions/helper/ContactPermissionHelper.kt, sample/android/src/main/AndroidManifest.xml, sample/ios/Calf/Info.plist
- Implement read contact permission request for Android and iOS
=> Add read contacts permission

README.md, calf-ui/src/commonMain/kotlin/com/mohamedrejeb/calf/ui/sheet/AdaptiveBottomSheet.kt, calf-ui/src/iosMain/kotlin/com/mohamedrejeb/calf/ui/datepicker/AdaptiveDatePicker.ios.kt, calf-ui/src/iosMain/kotlin/com/mohamedrejeb/calf/ui/sheet/AdaptiveBottomSheet.ios.kt, calf-ui/src/materialMain/kotlin/com/mohamedrejeb/calf/ui/sheet/AdaptiveBottomSheet.material.kt, gradle/libs.versions.toml, kotlin-js-store/yarn.lock
- Update Compose to 1.7.0
- Update Kotlin to 2.0.21
- Updates for some deps used only in sample
Closes: #190
=> Update Compose to 1.7.0

calf-permissions/src/androidMain/kotlin/com/mohamedrejeb/calf/permissions/PermissionsUtil.android.kt
=> Fix: Storage permission is not granted but returns granted

calf-ui/src/iosMain/kotlin/com/mohamedrejeb/calf/ui/datepicker/AdaptiveDatePickerState.ios.kt, calf-ui/src/iosMain/kotlin/com/mohamedrejeb/calf/ui/datepicker/DatePickerManager.kt
=> Fix UIDatePicker is always in UTC time

calf-permissions/src/commonMain/kotlin/com.mohamedrejeb.calf/permissions/MultiplePermissionsState.kt, calf-permissions/src/commonMain/kotlin/com.mohamedrejeb.calf/permissions/PermissionState.kt, gradle/libs.versions.toml, sample/android/build.gradle.kts, sample/android/src/main/java/com/mohamedrejeb/calf/sample/PermissionScreenPreview.kt
=> Make permissions work with Android Studio Preview

calf-ui/src/iosMain/kotlin/com/mohamedrejeb/calf/ui/datepicker/DatePickerManager.kt, calf-ui/src/iosMain/kotlin/com/mohamedrejeb/calf/ui/timepicker/TimePickerManager.kt
closes #210 
This pull request includes significant updates to the `DatePickerManager` and `TimePickerManager` classes in the `calf-ui` module for iOS. The changes focus on refactoring the code to improve the handling of date and time picker events by using `NSObject` delegates.
Refactoring for event handling:
* [`calf-ui/src/iosMain/kotlin/com/mohamedrejeb/calf/ui/datepicker/DatePickerManager.kt`](diffhunk://#diff-d2f928e8724cf34e82ed2fbf52d95d9791909792d839b027450771beb2933e77L44-R50): Replaced the use of method pointers and direct actions with an `NSObject` delegate to handle the date change events in the `DatePickerManager` class. [[1]](diffhunk://#diff-d2f928e8724cf34e82ed2fbf52d95d9791909792d839b027450771beb2933e77L44-R50) [[2]](diffhunk://#diff-d2f928e8724cf34e82ed2fbf52d95d97919097 …
=> fixed crash on time picker and date picker click

calf-ui/src/iosMain/kotlin/com/mohamedrejeb/calf/ui/timepicker/AdaptiveTimePickerState.ios.kt, sample/common/src/commonMain/kotlin/com.mohamedrejeb.calf.sample/screens/TimePickerScreen.kt
=> Fix hour and minute state initialization in AdaptiveTimePickerState

calf-ui/src/iosMain/kotlin/com/mohamedrejeb/calf/ui/sheet/AdaptiveBottomSheet.ios.kt, calf-ui/src/iosMain/kotlin/com/mohamedrejeb/calf/ui/sheet/BottomSheetManager.kt
=> Hide iOS drag handle on AdaptiveBottomSheet when dragHandle parameter is null

calf-permissions/src/androidMain/kotlin/com/mohamedrejeb/calf/permissions/PermissionsUtil.android.kt, calf-permissions/src/commonMain/kotlin/com.mohamedrejeb.calf/permissions/PermissionState.kt, calf-permissions/src/iosMain/kotlin/com.mohamedrejeb.calf/permissions/PermissionsUtil.ios.kt, sample/android/src/main/AndroidManifest.xml
reference from the documentation: https://developer.android.com/develop/sensors-and-location/location/permissions
fixes:#281 
@MohamedRejeb
=> add ability to request ACCESS_BACKGROUND_LOCATION permission starting from android 10+

gradle/libs.versions.toml
=> bumping libs versions
